# Generated by Django 5.1.3 on 2024-12-03 07:25

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("social_code", models.CharField(max_length=10, unique=True)),
                ("birth_date", models.DateField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("province", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=300)),
                ("phone_number", models.CharField(max_length=11)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("social_code", models.CharField(max_length=10, unique=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("province", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=300)),
                ("phone_number", models.CharField(max_length=11)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
