# Generated by Django 5.1.3 on 2024-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_providerprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="providerprofile",
            options={"ordering": ["user"]},
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="providerprofile",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("VF", "Verified"),
                    ("PN", "Verfication pending"),
                    ("DC", "Declined"),
                ],
                default="PN",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("VF", "Verified"),
                    ("PN", "Verfication pending"),
                    ("DC", "Declined"),
                ],
                default="PN",
                max_length=2,
            ),
        ),
    ]
