# Generated by Django 5.1.3 on 2024-12-09 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_providerprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={"ordering": ["user", "social_code"]},
        ),
        migrations.AlterModelOptions(
            name="providerprofile",
            options={"ordering": ["user", "official_name"]},
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["social_code"], name="account_cus_social__315f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["social_code"], name="account_pro_social__22e6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["official_name"], name="account_pro_officia_a84cac_idx"
            ),
        ),
    ]
