# Generated by Django 5.1.3 on 2024-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_customerprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="social_code",
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="social_code",
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
