# Generated by Django 5.1.3 on 2025-02-14 09:21

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_customerprofile_social_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="address",
            field=models.CharField(max_length=300, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="birth_date",
            field=models.DateField(verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number2",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="phone number 2"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="province",
            field=models.CharField(max_length=200, verbose_name="province"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="social_code",
            field=models.CharField(
                default=None, max_length=10, unique=True, verbose_name="Social Code"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("VF", "Verified"),
                    ("PN", "Verfication pending"),
                    ("DC", "Declined"),
                ],
                default="PN",
                max_length=2,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="address",
            field=models.CharField(max_length=300, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="provider name"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="official_name",
            field=models.CharField(max_length=100, verbose_name="official name"),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="phone_number2",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="phone number 2"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="province",
            field=models.CharField(max_length=200, verbose_name="province"),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="social_code",
            field=models.CharField(
                default=None, max_length=10, unique=True, verbose_name="social code"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("VF", "Verified"),
                    ("PN", "Verfication pending"),
                    ("DC", "Declined"),
                ],
                default="PN",
                max_length=2,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="providers_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
