# Generated by Django 5.1.3 on 2024-12-16 07:26

import django.db.models.deletion
import django.utils.timezone
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0006_alter_customerprofile_social_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.CharField(max_length=250, unique=True)),
                (
                    "properties",
                    models.JSONField(
                        validators=[items.models._validate_item_properties]
                    ),
                ),
                ("description", models.TextField()),
                ("remaining_items", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("publish", models.DateTimeField(
                    default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("VF", "Verified"),
                            ("PN", "Verfication pending"),
                            ("DC", "Declined"),
                        ],
                        default="PN",
                        max_length=2,
                    ),
                ),
                ("submission_review_message", models.TextField(null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.providerprofile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-publish", "slug"],
                "indexes": [
                    models.Index(
                        fields=["-publish"], name="items_item_publish_d84216_idx"
                    ),
                    models.Index(fields=["slug"],
                                 name="items_item_slug_d94d1c_idx"),
                ],
            },
        ),
    ]
