# Generated by Django 5.1.3 on 2024-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="submission_review_message",
            field=models.TextField(default="", null=True),
        ),
    ]
