# Generated by Django 5.1.3 on 2025-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_category_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["slug"]},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["slug"], name="items_categ_slug_1f2c47_idx"),
        ),
    ]
