# Generated by Django 5.1.3 on 2025-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_shoppingcartitem_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.TextField(
                choices=[("USD", "USA Dollar"), ("IRR", "Iranian Rial")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
