# Generated by Django 5.1.3 on 2025-01-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0011_alter_item_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcartitem",
            name="payment_id",
        ),
    ]
