# Generated by Django 5.1.3 on 2025-02-14 09:21

import django.db.models.deletion
import django.utils.timezone
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_customerprofile_address_and_more"),
        ("items", "0013_item_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="items.category",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.TextField(
                choices=[("USD", "USA Dollar"), ("IRR", "Iranian Rial")],
                default="USD",
                max_length=3,
                verbose_name="currency",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=items.models._item_image_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=250, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="properties",
            field=models.JSONField(
                validators=[items.models._validate_item_properties],
                verbose_name="properties",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.providerprofile",
                verbose_name="provider",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="publish"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="remaining_items",
            field=models.PositiveIntegerField(
                default=0, verbose_name="remaining items"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="item",
            name="submission_review_message",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="submission review message",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("VF", "Verified"),
                    ("PN", "Verfication pending"),
                    ("DC", "Declined"),
                ],
                default="PN",
                max_length=2,
                verbose_name="submission status",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="additional_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="additional info"
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="date updated"),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="items.item",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="properties",
            field=models.JSONField(verbose_name="properties"),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="quantity"),
        ),
    ]
