# Generated by Django 5.1.3 on 2025-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_alter_category_name_alter_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="image"),
        ),
    ]
