# Generated by Django 5.1.3 on 2025-02-14 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_alter_category_name_alter_category_parent_and_more"),
        ("orders", "0002_order_payment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="payment id"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PN", "Pending"),
                    ("PA", "Payment Accepted"),
                    ("PD", "Payment Declined"),
                    ("CN", "Canceled"),
                ],
                default="PN",
                max_length=2,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="items.item",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="orders.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="properties",
            field=models.JSONField(verbose_name="properties"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sku",
            field=models.SlugField(default=None, max_length=255, verbose_name="sku"),
        ),
    ]
