# Generated by Django 5.1.3 on 2025-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteVisitTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("counter", models.PositiveIntegerField(default=1)),
                ("first_encounter", models.DateTimeField(auto_now_add=True)),
                ("last_encounter", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(default="", max_length=50)),
            ],
            options={
                "ordering": ["-last_encounter", "-first_encounter"],
                "indexes": [
                    models.Index(
                        fields=["-last_encounter"],
                        name="tracker_sit_last_en_9bdcac_idx",
                    )
                ],
            },
        ),
    ]
