# Generated by Django 5.1.3 on 2025-05-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitTrackerVisitedPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_paths",
                        to="tracker.sitevisittracker",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "ip"],
                "indexes": [
                    models.Index(fields=["ip"], name="tracker_sit_ip_id_118af4_idx")
                ],
            },
        ),
    ]
